version: "3"

services:
  app:
    env_file:
      - ./.env
    depends_on:
      - "mongodb"
      - "redis"
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: npm start
    volumes:
      - .:/usr/src/app

    restart: always

  mongodb:
    env_file:
      - ./.env
    image: "mongo:4.2"
    volumes:
      - $PWD/data/mongodb:/data
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"

    restart: always

  redis:
    env_file:
      - ./.env
    image: "redis:alpine"
    command: redis-server

    ports:
      - "6379:${REDIS_PORT}"

    volumes:
      - $PWD/data/redis-data:/var/lib/redis

volumes:
  mongodb:
  app:
  redis:
